# Training
batch_size: 128
image_size: 64 # Resize images to 64x64 as per DCGAN requirements
latent_dim: 100 # Latent vector size (generator input)
img_channels: 1 # Number of image channels (FashionMNIST is grayscale)
num_classes: 10 # FashionMNIST has 10 classes
learning_rate: 0.0002 # Learning rate
beta1: 0.5 # Beta1 hyperparameter for Adam optimizer
epochs: 20 # Number of training epochs
n_critic: 5 # Number of critic iterations per generator iteration
weight_clip_value: 0.01 # Weight clipping value for WGAN
